server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location ~* \.(html|md)$ {
    add_header Cache-Control "no-cache";
    try_files $uri $uri/ =404; 
  }

  location ~* \.(css|js)$ {
    add_header Cache-Control "no-cache";
    try_files $uri =404;
  }

  location ~* \.(png|jpg|jpeg|gif|svg|ico|webp|woff|woff2)$ {
    expires 7d;
    add_header Cache-Control "public";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}