apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
labels:
  - pairs:
      app.kubernetes.io/instance: www-fintlabs
      fintlabs.no/org-id: fintlabs.no