apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application.yaml
commonLabels:
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/part-of: www-fintlabs
  fintlabs.no/team: core
  fintlabs.no/org-id: fintlabs.no