name: Cluster deploy

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: string
      image-tags:
        description: "Docker image with tag"
        required: true
        type: string

jobs:
  deploy-to-cluster:
    name: Deploy to Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Bake manifests with Kustomize
        id: bake
        uses: azure/k8s-bake@v3
        with:
          renderEngine: "kustomize"
          kustomizationPath: "kustomize/overlays/${{ inputs.environment }}"

      - uses: azure/login@v2
        with:
          creds: "${{ secrets[format('AKS_{0}_FINT_GITHUB', inputs.environment)] }}"

      - name: Set the target cluster
        uses: azure/aks-set-context@v4
        with:
          cluster-name: "${{ vars[format('{0}_CLUSTER_NAME', inputs.environment)] }}"
          resource-group: "${{ vars[format('{0}_CLUSTER_RESOURCE_GROUP', inputs.environment)] }}"
          admin: "true"
          use-kubelogin: "true"

      - name: Deploy
        uses: azure/k8s-deploy@v5.0.4
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: ${{ inputs.image-tags }}
          pull-images: false
          namespace: fintlabs-no
