name: Deploy to Firebase
on:
  push:
    branches:
      - master
      - CT-1211-reorganize-site

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        # Version 13.6.1 didnt work
        #uses: w9jds/firebase-action@master
        uses: w9jds/firebase-action@v13.6.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CI }}
